export const questions = [
  "What does inner peace mean to you, and when do you feel closest to it?",
  "If you could describe your life’s purpose in just one sentence, what would it be?",
  "When do you feel most connected to something bigger than yourself?",
  "What does forgiveness mean to you, and how do you practice it (toward yourself or others)?",
  "Have you ever had a moment that completely shifted your perspective on life? What happened?",
  "If you could sit in absolute silence for an hour and ask your heart any question, what would it be?",
  "What personal belief have you held for the longest, and why do you think it remains so important to you?",
  "Who in your life inspires you to grow spiritually, and what do you admire about them?",
  "What’s one value you strive to live by every day, and how do you incorporate it into your routine?",
  "If you could master the art of being fully present, how do you think it would change your daily life?",
  "What’s your favorite way to reconnect with yourself when you feel overwhelmed or lost?",
  "(Funny) If your soul had a theme song, what would it be and why?",
  "How do you measure success in your spiritual or personal journey, and how close do you feel you are to it?",
  "(Funny) If you could only eat one food for the rest of your life, what would it be—and would you still love it a year from now?",
  "Is there a fear or limiting belief that you’re actively working to overcome? How are you tackling it?",
  "What does living authentically look like for you, and where do you still feel challenged to be your true self?",
  "If you could spend a day with your younger self, how would you guide them differently—or would you?",
  "What role does gratitude play in your daily life, and how do you express it?",
  "If someone wrote a book about your spiritual journey so far, what would the title be?",
  "What kind of legacy do you hope to leave behind for future generations?",
  "(Funny) If you could learn one completely random skill (like yodeling or extreme unicycling), which would you pick and why?",
  "(Funny) If the universe had a knock-knock joke for you, how do you imagine the punchline would go?",
  "When was the last time you felt a powerful sense of wonder, and what triggered it?",
  "What’s one question about life or spirituality you still haven’t found an answer to, but would love to explore further?",
];
